apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alphaforge.fullname" . }}-secrets
type: Opaque
stringData:
  JWT_SECRET_KEY: {{ .Values.secrets.jwtSecretKey | quote }}
  ETHERSCAN_API_KEY: {{ .Values.secrets.etherscanApiKey | quote }}
  BSCSCAN_API_KEY: {{ .Values.secrets.bscscanApiKey | quote }}
  POLYGONSCAN_API_KEY: {{ .Values.secrets.polygonscanApiKey | quote }}
