apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.example.yaml
  - postgres.yaml
  - redis.yaml
  - kafka.yaml
  - clickhouse.yaml
  - api.yaml
  - ingestor.yaml
  - ml.yaml
  - worker.yaml
  - notifier.yaml
  - auditor.yaml
  - frontend.yaml
  - hpa.yaml
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/part-of: alphaforge
